//============================================================================
// Name        : AutogeneratedHello.cpp
// Author      : Peter
// Version     :
// Copyright   : IFS
// Description : Hello World in C++, Ansi-style
//============================================================================

#include <iostream>
using namespace std;

int main() {
	cout << "!!!Hello World!!!" << endl; // prints !!!Hello World!!!
	return 0;
}
